export const language = [
    {
        link: '/',
        label: "ENG",
        value: "/en",
        title: 'SKYREX BLOG',
        authButton: 'START FOR FREE',
        home: 'GO TO MAIN PAGE',
        copy: 'SKYREX . ALL RIGHTS RESERVED.',
        privacy: "PRIVACY & TERMS",
        labelTraiding: 'TRADING RESULTS',
        balanceStart: 'Start balance',
        balanceCurr: 'Current balance',
        profit: 'Profit',
        dur: 'Av. deal duration',
        trades: 'Trades / successfull',
        rate: 'Success rate',
        labelProfit: 'SUMMARY PROFIT, $',
        labelAsset: 'PROFIT BY ASSET, $',
        labelDay: 'PROFIT BY DAY, $',
        labelHistory: 'History',
        top: 'Top deals',
        search: 'Search',
        mins: ['minute', 'minutes', 'minutes'],
        hours: ['hour', 'hours', 'hours'],
        days: ['day', 'days', 'days'],
        patrTrade: 'Pair',
        startDateTabel: 'Start Date',
        endDateTable: 'End Date',
        durTable: 'Duration',
        safetiesTable: 'Safeties',
        profitTable: 'Profit, USDT',
        totalTable: 'Accumulated profit, Total'
    },
    {
        link: '/',
        label: "RU",
        value: "/ru",
        title: 'SKYREX БЛОГ',
        authButton: 'НАЧАТЬ БЕСПЛАТНО',
        home: 'НА ГЛАВНУЮ',
        copy: 'SKYREX . ВСЕ ПРАВА ЗАЩИЩЕНЫ.',
        privacy: "ЗАЩИТА & УСЛОВИЯ",
        labelTraiding: 'РЕЗУЛЬТАТЫ ТРЕЙДА',
        balanceStart: 'Стартовый баланс',
        balanceCurr: 'Текущий баланс',
        profit: 'Профит',
        dur: 'Продолжительность сделки',
        trades: 'Трейды / успешные',
        rate: 'Успешые сделки',
        labelProfit: 'СУМАРНЫЙ ПРОФИТ, $',
        labelAsset: 'ПРОФИТ ЗА СДЕЛКУ, $',
        labelDay: 'ПРОФИТ ЗА ДЕНЬ, $',
        labelHistory: 'История',
        search: 'Поиск',
        top: 'Топ сделки',
        mins: ['минута', 'минуты', 'минут'],
        hours: ['час', 'часа', 'часов'],
        days: ['день', 'дня', 'дней'],
        patrTrade: 'Pair',
        startDateTabel: 'Начало трейда',
        endDateTable: 'Конец трейла',
        durTable: 'Продолжительность сделки',
        safetiesTable: 'Безопасность',
        profitTable: 'Профит, USDT',
        totalTable: 'Общий профит, Всего'
    }
]

export const domain = `http://89.108.77.121:5000`
export const develop = `http://localhost:5000`
export const build = false

export const topdeals = 800